language: ruby
rvm:
- 2.6.2
- ruby-head
# gemfile: "gems.rb"
addons:
  postgresql: "9.6"
before_install:
- gem install bundler
before_script:
- cp config/.travis.database.yml config/database.yml
- psql -c 'create database travis_test;' -U postgres
matrix:
  allow_failures:
  - rvm: ruby-head
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: us-east-1
  app: helpds.study
  env: help-ds-production
  bucket_name: elasticbeanstalk-us-east-1-891922105393
  on:
    repo: sleepepi/helpds.study
    branch: master
    rvm: 2.6.2
